### ISSUE TITLE
Search Implemented and redesigned from scratch

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#615]
# Epic
Search Implemented and redesigned from scratch

# Value 
(Expected value to consumer when epic is implemented) 

# Acceptance Criteria 
- [ ] 

# Milestones 
- [x] Design a new architecture for Search
- [ ] Design and implement the new schema based on the the new architecture
- [ ] Search and Queries implementation
- [ ] Infrastructure and indexing policies
- [ ] Phase out the old version
- [ ] Plan and communicate releases for redesigned search

**Comment by akatsoulas** [comment]
Milestones for this Epic:
- [ ] https://github.com/mozilla/sumo-project/milestone/15
- [ ] https://github.com/mozilla/sumo-project/milestone/16

**Comment by madasan** [comment]
Adding milestone:
- [ ] [Plan and communicate releases for redesigned search](https://github.com/mozilla/sumo-project/milestone/26)
