### ISSUE TITLE
Enhance Search through new functionality

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#618]
# Epic
Enhance Search with new functionality - After achieving 1:1 parity with the current search, we should focus on how to further improve the user experience.

# Description 
We expect that the experience of our users will be improved with the completion of the first epic by offering a more performant search which will provide better search results to our users. When this is achieved we can further improve it by:

- [ ] Simplifying the complexity of the advanced search.
> - [ ] Allow users to select/focus the search on specific data by providing for example checkboxes under the search bar. Eg [ ] Wiki, [ ] AAQ, [ ] Users - This will allow us to completely remove fields from the advanced search such as searching on users with a simple enough solution
> - [ ] Deprecate searching on fields that are not relevant or are not used any more - We should explore what data are not used any more through Google Analytics and completely remove them
> - [ ] Allow filtering on specific fields by using specific notation (eg search_term :my_field) 
> - [ ] Allow matching the exact phrase by using double quotes
> - [ ] Revisit weights on specific data to optimize ranking on important indices/fields

- [ ] Adding more features
> - [ ] Fuzyy search and auto correction
> - [ ] Auto-complete search terms for the main indices (KB and AAQ)
> - [ ] Explore the  option to use ElasticSearch’s built in ML capabilities to track abnormal patterns. Eg a spike in questions for a specific release
> - [ ] Allow boolean searches (X :not Y)
> - [ ] Use synonyms to improve search results. React and ReactJS

- [ ] Refining the UI
> - [ ] Optimize the page under /search URL to include all the above options or to provide some help text/guidance on how to use the features

- [ ] Provide more data points both to our user base and to Mozilla Staff.
> - [ ] Work with the CX team to get an initial list of aggregations that we are interested in - Eg how many users had 3 answers within a week
> - [ ] Explore self-hosted/cloud options to have a Kibana dashboard available to team/Mozilla to visualize data
> - [ ] Fix broken dashboards
> - [ ] Update existing dashboard to use the new search
> - [ ] Explore options on different visualization strategies

**Comment by akatsoulas** [comment]
Milestones for this Epic:
- [ ] [Move advanced search functionality to /search](https://github.com/mozilla/sumo-project/milestone/20)
- [ ] [Enhance SUMO search (fuzzy, boolean, synonyms, ML)](https://github.com/mozilla/sumo-project/milestone/21)
- [ ] [Search and SUMO UI](https://github.com/mozilla/sumo-project/milestone/22)
- [ ] [Aggregations and Data extractions](https://github.com/mozilla/sumo-project/milestone/23)

**Comment by JakeQZ** [comment]
Does this apply to 'Firefox Help', i.e. the [page arrived at via ≡ > Help > Firefox Help](https://support.mozilla.org/en-US/products/firefox?as=u&utm_source=inproduct) from within Firefox?

If so, I would suggest extending 'Adding more features' to include phrases in "quotation marks" - see https://bugzilla.mozilla.org/show_bug.cgi?id=1666052
